### ISSUE TITLE
Show verbose command 

### ISSUE THREAD

**Issue by gopar** [federicotdn/verb#11]
Hey,

Is it possible to show the complete command that `verb` uses to make the http call when using curl?

For example it would show something like this
```
curl \
   -D- \
   -X POST \
   --data {body that is passed} \
   -H "Content-Type: application/json" \
   http://localhost:8080/rest/api/2/
```

The reason I'm asking this is to figure out what `verb` is doing b/c when calling an external program like `curl` to the desired api call i'm making succeeds without any issue but when using `verb` I start to get errors (eg, status codes 415, etc). Love the package and want to continue using it :)

**Comment by federicotdn** [comment]
Hey @gopar,
Verb uses the internal Emacs `url` library to send requests, it doesn't use curl.

If you wish to debug what's going on when Emacs sends the request, I recommend you do `(setq url-debug t)`, and then send your request again. After that, switch to the `*URL-DEBUG*` buffer to see what `url` has logged.

Do you have more details on the request that's breaking on Verb but not on curl? I'd be interested in fixing that!

**Comment by federicotdn** [comment]
Closing as Verb does not use `curl` as a backend.
