### ISSUE TITLE
Option to not use side-window for response/header buffers

### ISSUE THREAD

**Issue by paulbdavis** [federicotdn/verb#12]
I'm using `frames-only-mode` and it would be nice to be able to set the option for the response buffers to be normal rather than side windows, this way they will open up like most other buffers thus creating a new frame with `frame-only-mode` enabled.

Looking at the source I don't see `display-buffer-in-side-window` used anywhere... not sure where to start hacking on that (from what I can tell it just switches to it in another window normally)

**Comment by federicotdn** [comment]
Hey @paulbdavis,

To switch to the response buffer, I'm actually using the `switch-to-buffer-*` functions (see [here](https://github.com/federicotdn/verb/blob/master/verb.el#L1511)). I'm not sure how they work exactly with `frames-only-mode`, I tried them quickly and it seemed to work correctly (the responses where shown in separate frames).

To show the response headers, I'm actually using an ugly `verb--split-window` function (see [here](https://github.com/federicotdn/verb/blob/master/verb.el#L996)). Unfortunately that is not compatible with `frames-only-mode`, but I am open to suggestions on how this could be changed to make it compatible (maybe use `display-buffer`?)

**Comment by federicotdn** [comment]
I've pushed 542a98712bf764ae7aecc9941ee45d99e857a021 to master, which removes the `verb--split-window` function and replaces its uses with either `display-buffer` and/or `switch-to-buffer`. I believe this should make Verb completely compatible with `frames-only-mode`. Please check if this new change is working for you.

**Comment by paulbdavis** [comment]
I updated to 97e6434 and it's still opening up in a side window (if I change to the window and try to `C-x 1` it says it's a side window)

**Comment by federicotdn** [comment]
Interesting! I've tried using that same version of Verb, with the latest version of `frames-only-mode`, using `emacs -Q`. When I send a request with `C-c C-r C-r`, the response is opened on a new frame.

Maybe we're using different Emacs versions? I'm on 26.3 currently. Or maybe you have some customizations applied on top of `frames-only-mode`. Could you could try with `emacs -Q` as well loading only Verb and `frames-only-mode`?

When I'm on `emacs -Q` with `frames-only-mode`, calling `(switch-to-buffer-other-window "*scratch*")` effectively opens a new frame, which is the same function Verb uses when `C-c C-r C-r` is pressed. It would be interesting to test that on your setup as well.

**Comment by paulbdavis** [comment]
This was on emacs 27 (not sure which specific revision, it was from before release). I'll try to reproduce with emacs -Q and report back

**Comment by federicotdn** [comment]
Thanks for that. In either case, there's also the option of modifying Verb itself so that it adapts better to frame-only workflows (e.g. like adding a user variable `verb-use-frames` or similar). That may also be useful for people that prefer frames but that don't use `frames-only-mode`.

**Comment by paulbdavis** [comment]
Hm, so when I start emacs with `emacs -Q` and load up the packages:

```elisp
(add-to-list 'load-path "/home/paul/.config/emacs/straight/build/verb")
(add-to-list 'load-path "/home/paul/.config/emacs/straight/build/frames-only-mode")
(add-to-list 'load-path "/home/paul/.config/emacs/straight/build/dash")
(add-to-list 'load-path "/home/paul/.config/emacs/straight/build/s")

(require 'frames-only-mode)
(require 'verb)
(frames-only-mode)
```

Everything works as I would expect, even after applying my other settings in my init.el. There must be something else interacting with it. Closing this for now as it's not actually an issue with either package.
