### ISSUE TITLE
Can verb support run from command line?

### ISSUE THREAD

**Issue by peng051410** [federicotdn/verb#13]
Can I execute the request from the command line? for example:
`emacs -nw -Q --eval (verb-send-request-xxxx)`

**Comment by federicotdn** [comment]
Hey @peng051410! Thanks for your interest in the project.

What you mention is an interesting use case, I hadn't considered it. How would you specify the request to be made to Verb itself? I can imagine two options: the first one, reading the request from stdin:

```bash
$ echo 'get http://example.com/api/users' | emacs -nw -Q --eval (verb-send-request-xxxx)
```

Or the second one, reading a request from a file:

```bash
$ emacs -nw -Q --eval '(verb-send-request-xxxx "filename.org" "Heading Title")'
```

And then, what would you output then? It could be just the request body, or maybe the body and the headers.

**Comment by peng051410** [comment]
I am very interested in the implementation of the second, and if so, I will call cass with other tools

**Comment by federicotdn** [comment]
I think this type of usage is better fit for a tool like `curl`. Using Verb in batch mode implies that you lose some of the interactive functionality like `verb-var` or `C-u C-c C-r C-r` etc., and at that point `curl` makes more sense to use.

To see if it was possible though, I wrote this small function:
```elisp
(defun verb-send-from-file (filename heading)
  "Send an HTTP request stored in FILENAME under HEADING."
  (find-file filename)
  (goto-char (point-min))
  (re-search-forward (regexp-quote heading))
  (with-current-buffer (verb-send-request-on-point nil)
    (while (eq verb-http-response t)
      (sleep-for 0.01))
    (princ (verb-response-to-string verb-http-response
				    (current-buffer)))))

```

Which can be used like this (assuming the function is stored in `function.el` in the cwd, and `verb.el` is in the cwd as well):

```bash
$ emacs -l verb.el -l function.el --batch --eval '(verb-send-from-file "my-file.org" "** My Heading")'
```

Hope it helps!

**Comment by peng051410** [comment]
Thank you very much!
