### ISSUE TITLE
Feature Request - make output buffer mode configurable

### ISSUE THREAD

**Issue by peterhoeg** [federicotdn/verb#16]
Currently the results buffer is forced to `js-mode` ref https://github.com/federicotdn/verb/blob/master/verb.el#L1271 

It would be great if that could be configurable as emacs has a `json-mode`. Some people might prefer `js2-mode` and so on.

**Comment by federicotdn** [comment]
Hey @peterhoeg, you technically could do this by customizing the `verb-content-type-handlers` variable, and adding your own handler for `application/json`. But maybe it would be easier for users to just use the default handler (`verb--handler-json`), but allow customizing what mode that function uses internally (currently it's `js-mode`, as you said). What do you think?

**Comment by peterhoeg** [comment]
I did actually have a look at verb-content-type-handlers before opening this
	issue when I was looking at how the mode was being determined but thought
	this would be something others would like too hence the request for a knob.

>   default handler (verb--handler-json), but allow customizing what mode that
>   function uses internally (currently it's js-mode, as you said). What do
>   you think?

Yes, that sounds like the plan.

**Comment by peterhoeg** [comment]
Strange, this seems to completely break verb for me. 

If I try doing a request that definitely worked earlier in the week, it simply sits there and doesn't produce any output into the HTTP buffer.

Calling the curl export function and running that in a terminal works.

The only odd thing abou this setup is that it is over an SSH tunnel (the endpoint uses an IP whitelist), so for curl I need to add `-k` to disable cert verification, but I already do that with `(setq gnutls-verify-error nil)`.

But again, this worked on Thu or Fri.

<details>

```
GET request sent to https://localhost:40443/papi/Purchase/Invoices/Companies
gnutls.c: [1] (Emacs) connecting to host: localhost
gnutls.c: [1] (Emacs) allocating credentials
gnutls.c: [2] (Emacs) allocating x509 credentials
gnutls.c: [2] (Emacs) using default verification flags
gnutls.c: [1] (Emacs) setting the trustfile:  /etc/ssl/certs/ca-certificates.crt
gnutls.c: [1] (Emacs) setting the trustfile:  /etc/pki/tls/certs/ca-bundle.crt
gnutls.c: [1] (Emacs) gnutls callbacks
gnutls.c: [1] (Emacs) gnutls_init
gnutls.c: [1] (Emacs) got non-default priority string: SECURE128:+SECURE192:-VERS-ALL:+VERS-TLS1.2:+VERS-TLS1.3
gnutls.c: [1] (Emacs) setting the priority string
gnutls.c: [2] added 2 protocols, 29 ciphersuites, 17 sig algos and 10 groups into priority list
gnutls.c: [2] Keeping ciphersuite 13.02 (GNUTLS_AES_256_GCM_SHA384)
gnutls.c: [2] Keeping ciphersuite 13.03 (GNUTLS_CHACHA20_POLY1305_SHA256)
gnutls.c: [2] Keeping ciphersuite 13.01 (GNUTLS_AES_128_GCM_SHA256)
gnutls.c: [2] Keeping ciphersuite 13.04 (GNUTLS_AES_128_CCM_SHA256)
gnutls.c: [2] Keeping ciphersuite c0.2c (GNUTLS_ECDHE_ECDSA_AES_256_GCM_SHA384)
gnutls.c: [2] Keeping ciphersuite cc.a9 (GNUTLS_ECDHE_ECDSA_CHACHA20_POLY1305)
gnutls.c: [2] Keeping ciphersuite c0.0a (GNUTLS_ECDHE_ECDSA_AES_256_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite c0.ad (GNUTLS_ECDHE_ECDSA_AES_256_CCM)
gnutls.c: [2] Keeping ciphersuite c0.2b (GNUTLS_ECDHE_ECDSA_AES_128_GCM_SHA256)
gnutls.c: [2] Keeping ciphersuite c0.09 (GNUTLS_ECDHE_ECDSA_AES_128_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite c0.ac (GNUTLS_ECDHE_ECDSA_AES_128_CCM)
gnutls.c: [2] Keeping ciphersuite c0.30 (GNUTLS_ECDHE_RSA_AES_256_GCM_SHA384)
gnutls.c: [2] Keeping ciphersuite cc.a8 (GNUTLS_ECDHE_RSA_CHACHA20_POLY1305)
gnutls.c: [2] Keeping ciphersuite c0.14 (GNUTLS_ECDHE_RSA_AES_256_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite c0.2f (GNUTLS_ECDHE_RSA_AES_128_GCM_SHA256)
gnutls.c: [2] Keeping ciphersuite c0.13 (GNUTLS_ECDHE_RSA_AES_128_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite 00.9d (GNUTLS_RSA_AES_256_GCM_SHA384)
gnutls.c: [2] Keeping ciphersuite 00.35 (GNUTLS_RSA_AES_256_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite c0.9d (GNUTLS_RSA_AES_256_CCM)
gnutls.c: [2] Keeping ciphersuite 00.9c (GNUTLS_RSA_AES_128_GCM_SHA256)
gnutls.c: [2] Keeping ciphersuite 00.2f (GNUTLS_RSA_AES_128_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite c0.9c (GNUTLS_RSA_AES_128_CCM)
gnutls.c: [2] Keeping ciphersuite 00.9f (GNUTLS_DHE_RSA_AES_256_GCM_SHA384)
gnutls.c: [2] Keeping ciphersuite cc.aa (GNUTLS_DHE_RSA_CHACHA20_POLY1305)
gnutls.c: [2] Keeping ciphersuite 00.39 (GNUTLS_DHE_RSA_AES_256_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite c0.9f (GNUTLS_DHE_RSA_AES_256_CCM)
gnutls.c: [2] Keeping ciphersuite 00.9e (GNUTLS_DHE_RSA_AES_128_GCM_SHA256)
gnutls.c: [2] Keeping ciphersuite 00.33 (GNUTLS_DHE_RSA_AES_128_CBC_SHA1)
gnutls.c: [2] Keeping ciphersuite c0.9e (GNUTLS_DHE_RSA_AES_128_CCM)
gnutls.c: [2] Advertizing version 3.3
gnutls.c: [2] Advertizing version 3.4
gnutls.c: [2] HSK[0x5b15860]: sent server name: 'localhost'
gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again. [4 times]
gnutls.c: [2] received curve X25519
gnutls.c: [1] (Emacs) non-fatal error: Resource temporarily unavailable, try again.
gnutls.c: [2] checking issuer DN
gnutls.c: [2] issuer in verification was not found or insecure; trying against trust list
gnutls.c: [2] checking issuer DN
gnutls.c: [2] (Emacs) Deallocating x509 credentials
Request to https://localhost:40443/papi/Purchase/Invoices/Companies is taking longer than expected
```
</details>

**Comment by federicotdn** [comment]
Hmmm that's strange, since I didn't really modify anything related to `url.el` (the change was super small, really, and not relating to the connection process). Could you try that again, but this time using the Verb version you were using previously?

**Comment by peterhoeg** [comment]
I'll try to do a bisect to find out where things break - realistically it will only be Tue or Wed.

**Comment by peterhoeg** [comment]
So `verb` is perfectly fine. It was a general `gnutls` issue on emacs. And this change works wonderfully as well, thank you!

**Comment by peterhoeg** [comment]
Closing as it was fixed in https://github.com/federicotdn/verb/commit/e56a4377fc1685f4408a4a27ad115c3f907513de
