### ISSUE TITLE
Non-verb Babel source blocks for bodies

### ISSUE THREAD

**Issue by sulami** [federicotdn/verb#17]
I'm using verb for several REST APIs which have some quite large JSON bodies in requests. I'd really appreciate if I could use a source block to be able to use `org-edit-special` and get proper syntax-highlighting/indentation/auto-completion instead of having to work in the org-file directly. verb seems to only support `verb-mode` source blocks, which do not satisfy this use case.

I'm wondering if there is a way this could be added/worked around? Ideally I'd like to see something like this:

```
* My request :verb:
post /api/v1/some/path/

#+begin_src js
{
  "some": "body"
}
#+end_src
```

**Comment by federicotdn** [comment]
Hey, thanks for bringing this up. I think it's a good idea, and the implementation for it will be relatively short I believe. I'll let you know when it's done.

**Comment by sulami** [comment]
Federico Tedin <notifications@github.com> writes:

> Hey, thanks for bringing this up. I think it's a good idea, and the
> implementation for it will be relatively short I believe. I'll let you
> know when it's done.

Thanks for the quick reply, and thanks for picking this up so quickly.
Let me know if I can do anything to help.

**Comment by federicotdn** [comment]
Thanks :+1: 
I've added this on `master`, please check if it works for you when MELPA builds it on the next run.

**Comment by sulami** [comment]
Federico Tedin <notifications@github.com> writes:

> Thanks :+1: 
> I've added this on `master`, please check if it works for you when
> MELPA builds it on the next run.

I just pulled and tried this, seems to work just as expected. Thanks for
the incredible turnaround!
