### ISSUE TITLE
Embedding requests and responses in an org document

### ISSUE THREAD

**Issue by DamienCassou** [federicotdn/verb#2]
Hi,

I've been using restclient for quite some time and your package seems a really nice improvement over it. I will try it. I especially like the fact that inner nodes inherit properties from their ancestors, making it easy to change the url or credentials.

Probably out of scope but still related: What I would really like is to have an org document with requests, answers and text describing both while keeping the inheritance of properties across nodes.

**Comment by federicotdn** [comment]
Thanks for the feedback!

In the future I might try switching from Outline to Org for this package. This should allow using Verb + all the Org utilities at the same time. Regarding the storage of responses, for this package I have decided not to have them included in the request files. Maybe it would be possible to store them on a separate file? E.g. if you had a `twitter-api.verb` file, then responses could be stored in a `twitter-api.verb-store` file, where each response would associated with a `Header 1/SubHeader A/SubSubHeader X` entry (linking back to the original verb file that did the request).

**Comment by DamienCassou** [comment]
> Maybe it would be possible to store them on a separate file?

You could certainly do that but that wouldn't be useful for me. I'm looking for a document which contains some story, some requests and some answers. Maybe an `ob-verb` package could be useful.

**Comment by DamienCassou** [comment]
You may close this issue. Thank you for answering.

**Comment by federicotdn** [comment]
No problem. I'll look more into this when I get around to making Verb use Org instead of Outline. I also like your idea of integrating it with Babel.

**Comment by federicotdn** [comment]
Hey @DamienCassou, I decided to migrate Verb to use Org mode, and I ended up implementing Babel integration as well. Here's the doc for the new feature: https://github.com/federicotdn/verb#babel-integration

(the package will be updated on the next MELPA build)

**Comment by taudep** [comment]
Really cool. I look forward to checking this out....
