### ISSUE TITLE
Feature request: integrate with auth-sources for reading tokens

### ISSUE THREAD

**Issue by stig** [federicotdn/verb#25]
I frequently use verb with APIs I need to authenticate with, and it would be nice if I could store the tokens in auth-sources. That would allow me to share the file with colleagues, without having to edit out the token first. `{{(verb-var token)}}` would work, but I'd have to manually paste the token every time I open the file.

-----

I'm experimenting with something like:

```emacs-lisp
  (defun sb/api-token-for-host (host)
    "Return a token for the specified host."
    (let ((found (nth 0 (auth-source-search :host host :create nil))))
      (when found
	(let ((secret (plist-get found :secret)))
	  (if (functionp secret)
	      (funcall secret)
	    secret)))))
```

I can use this like this `{{(sb/api-token-for-host "localhost")}}` but it would be nice if verb could automatically provide the host based on the template / request however.

**Comment by federicotdn** [comment]
Hey @stig, I'm thinking of ways of exposing the request information to the code being evaluated inside code tags but the thing is, when the tags are being evaluated, the request hasn't been built yet!

For your specific case, I can think of two solutions:
1) Use `verb-var` to set the `host`, and then re-use it with the function you wrote:
```
get http://{{(verb-var host)}}/api/foobar
Authentication: Bearer {{(sb/api-token-for-host (verb-var host))}}
```

2) Use a [request mapping function](https://github.com/federicotdn/verb#request-mapping-functions) that modifies the request before it is sent. It could insert a header programatically, reading the value using `auth-sources`:

```elisp
(defun insert-token (rs)
  (oset rs headers
        (append `(("Authorization" . ,(sb/api-token-for-host <Host from RS>)))
                (oref rs headers)))
  rs)
```

Would either work for your use case? Option 2 is uglier IMO.

**Comment by stig** [comment]
Either would probably work for me. I think I would prefer 1, especially if `verb-var` takes an optional third argument to use as a default. Then I could do and just hit return to accept the default "example.com" most times, but specify "localhost" if I do local dev. 

```
get http://{{(verb-var host "example.com")}}/api/foobar
Authentication: Bearer {{(sb/api-token-for-host (verb-var host))}}
```

**Comment by federicotdn** [comment]
That's exactly how it works! You won't get prompted though, it'll just silently be set to `example.com`. You can then quickly change it using <kbd>M-x</kbd> `verb-set-var`.

**Comment by stig** [comment]
Amazing! Thank you for being so responsive! This is the best.
