### ISSUE TITLE
URLs with underscores are displayed with org formatting

### ISSUE THREAD

**Issue by paulbdavis** [federicotdn/verb#3]
When there are underscores in URLs or in other stuff (like request bodies, headers) org mode displays them as being a subscript

`get /endpoint?page_size=99` turns into this:

![verb](https://user-images.githubusercontent.com/2730634/73100524-f096d280-3eaa-11ea-8926-8efaf858c010.png)

**Comment by federicotdn** [comment]
Hey @paulbdavis 

The docs for `org-use-sub-superscripts` mention this:
> Still, ambiguity is possible.  So when in doubt, use {} to enclose
> the sub/superscript.  If you set this variable to the symbol ‘{}’,
> the braces are *required* in order to trigger interpretations as
> sub/superscript.  This can be helpful in documents that need "_"
> frequently in plain text.

So maybe I could make `verb-mode` set buffer-locally this variable to `{}`, so that there's less change of this happening (but may still happen if you do `foo_{bar}`). What do you think of that?

**Comment by buicaocuong** [comment]
Vào 25-01-2020 03:11, "Paul Davis" <notifications@github.com> đã viết:
>
> When there are underscores in URLs or in other stuff (like request
bodies, headers) org mode displays them as being a subscript

**Comment by buicaocuong** [comment]
Hú

**Comment by buicaocuong** [comment]
9.uk

**Comment by federicotdn** [comment]
Let's try to keep the conversation on-topic. Thanks.

**Comment by federicotdn** [comment]
As I want to avoid messing with users' Org configs, for the moment I recommend you use file-locals to set `org-use-sub-superscripts` to `{}`:

```
# Local Variables:
# org-use-sub-superscripts: {}
# End:
```

Hope it's useful!

**Comment by paulbdavis** [comment]
Yeah, the local variable solution works well. You may consider adding it to the README.

**Comment by federicotdn** [comment]
Good idea, thanks.
