### ISSUE TITLE
verb-var does not accept var from og-mode bable block

### ISSUE THREAD

**Issue by davidshen84** [federicotdn/verb#33]
When trying to evaluate the 2nd block, Emacs prompted to input the value for *v*. Apparently, the `verb-var` function cannot read values provided by the `:var` keyword.

```
     #+name: ex
     #+begin_example
     json
     #+end_example

     #+begin_src verb :var v=ex
get https://reqbin.com/echo/get/{{(verb-var v)}}

     #+end_src
```

**Comment by federicotdn** [comment]
That is correct, Verb currently does not know how to read `var` Babel header arguments.

**Comment by federicotdn** [comment]
Implemented in https://github.com/federicotdn/verb/commit/f9e69bf42eb8108aeee020ed3f58f456e042967f.
