### ISSUE TITLE
ob-verb: only export response body

### ISSUE THREAD

**Issue by DamienCassou** [federicotdn/verb#6]
When using ob-verb, is it possible to only get the response body, omiting the response headers?

**Comment by federicotdn** [comment]
That’s a feature I haven’t added yet because I wasn’t sure what the ideal way to present it was.

Maybe the `:op send` argument could be expanded so that it now can take the value of `:op send get-headers` or `:op send get-body`? (Would default to `:op send get-all`)

**Comment by DamienCassou** [comment]
Federico Tedin <notifications@github.com> writes:
> Maybe the `:op send` argument could be expanded so that it now can
> take the value of `:op send get-headers` or `:op send get-body`?
> (Would default to `:op send get-all`)

This seems reasonable but I'm not an expect in org-babel.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by federicotdn** [comment]
> This seems reasonable but I'm not an expect in org-babel.
No problem; `:op` is just an argument I invented anyways. So we are free to choose how it works exactly.

**Comment by federicotdn** [comment]
Just pushed a new option to use `:op send get-headers` or `:op send get-body` on source blocks. It should be out on the next MELPA build.

**Comment by DamienCassou** [comment]
Awesome, it works great! Thank you.

**Comment by mpereira** [comment]
I apologize for commenting on a closed issue, but it seems relevant: does anyone know if it's feasible to make it possible to insert two separate result code blocks on `:op send get-all`? One for the header and the other for the body.

**Comment by federicotdn** [comment]
Hey! Unfortunately this seems to be a limitation of Babel. When you press C-c C-c, Babel takes the block's contents and sends them to `org-babel-execute:verb`, which itself returns a new string to be used as results. The `org-babel-execute:verb` function itself has no control on how the result is displayed exactly (only the contents).

However, there'll always be an empty line between the response headers and the response body, so separating them via a custom function shouldn't be too hard.

**Comment by mpereira** [comment]
I thought that could be the case. Thanks for letting me know!
