### ISSUE TITLE
Naming: "url schema" vs "url scheme"

### ISSUE THREAD

**Issue by vakili** [federicotdn/verb#61]
In several places (in the readme and in the source code), the term "url schema" is used to refer to e.g. `https`. This does not follow the standard terminology which is "url scheme". See: https://doi.org/10.17487%2FRFC3986 or https://en.wikipedia.org/wiki/URL#Syntax

**Comment by federicotdn** [comment]
Good catch! Fixed in https://github.com/federicotdn/verb/commit/b3e3c3eeea21ffa24f5dc8bef6dd401cc25c199a
Luckily "schema" was not part of any public function or variable
