### ISSUE TITLE
form-data key-value example

### ISSUE THREAD

**Issue by kostafey** [federicotdn/verb#76]
Is there some example of using a simple `form-data` post request?

E.g. (unfortunately, it doesn't work):
```
post http://127.0.0.1:9000/handler
Content-Type: form-data

"paramName": "paramValue"
```

**Comment by federicotdn** [comment]
Hi, do you mean [multipart/form-data](https://github.com/federicotdn/verb?tab=readme-ov-file#multipart-data)?

**Comment by kostafey** [comment]
If I write
```
post http://127.0.0.1:9000/handler
Content-Type: multipart/form-data

paramName = paramValue
```

It generates (to curl):
```sh
curl 'http://127.0.0.1:9000/handler' \
-H 'Content-Type: multipart/form-data' \
-X POST \
--data-raw 'paramName = paramValue'
```

but I need the following one:
```sh
curl 'http://127.0.0.1:9000/handler' \
-H 'Content-Type: multipart/form-data' \
-X POST \
-F 'paramName = paramValue'
```

**Comment by kostafey** [comment]
The actual solution is:
```
post http://127.0.0.1:9000/handler
Content-Type: application/x-www-form-urlencoded

paramName=paramValue
```
(necessarily without spaces).

Would you like to add it to the README? Or can I add a pull request myself?

**Comment by federicotdn** [comment]
I don't think it is necessary to add to the README, since specifying that header value + the body format is not doing anything Verb-specific, just using Verb as it is intended to be used. Thank you for offering though.
