### ISSUE TITLE
Set variables in the buffer/file, per request

### ISSUE THREAD

**Issue by federicotdn** [federicotdn/verb#78]
### Discussed in https://github.com/federicotdn/verb/discussions/72

<div type='discussions-op-text'>

<sup>Originally posted by **jjnilton** July  5, 2024</sup>
Related: https://github.com/federicotdn/verb/issues/27

Currently, it seems that the ways to set variables for a request are:
1. Using `{{(verb-set-var "var-name" "var-value")}}` inline;
2. Adding `#Local variables:` at the end of the file/buffer;
3. Using an external file and the `Verb-Prelude` property.

The option 1 can get verbose depending on the variables, and not as easy to read them.
The option 2 affects all requests in the file/buffer and must be added at the end, so it can be harder to track what are the variables if the file has other stuff besides the requests.
The option 3 requires an external file, and sometimes seems a bit much for simple stuff.

I'm coming from restclient.el, so there I used to something like this:
```
:id=73c02a16-99b9-4ab0-8fd0-fd31a92298f1
:anotherId=8491d155-edd8-4831-9e6a-32d939cd35c5
get http://endpoint.test/test?id=:id&anotherId=:anotherId
```

In verb, I have to do something like this:
```org
* Current
get http://endpoint.test/test?id={{(verb-set-var "id" "73c02a16-99b9-4ab0-8fd0-fd31a92298f1")}}&anotherId={{(verb-set-var "anotherId" "8491d155-edd8-4831-9e6a-32d939cd35c5")}}
```

My suggestion would be to do something like this:
```
* Suggestion
:properties:
:Verb-Variable: (id "73c02a16-99b9-4ab0-8fd0-fd31a92298f1")
:Verb-Variable: (anotherId "8491d155-edd8-4831-9e6a-32d939cd35c5")
:end:
get http://endpoint.test/test?id={{(verb-var id)}}&anotherId={{(verb-var anotherId)}}
```

Or maybe:

```
* Suggestion
verb-var id "73c02a16-99b9-4ab0-8fd0-fd31a92298f1"
verb-var anotherId "8491d155-edd8-4831-9e6a-32d939cd35c5"
get http://endpoint.test/test?id={{(verb-var id)}}&anotherId={{(verb-var anotherId)}}
```

It's still more boilerplate because of the drawer, properties and how verb reads the variable, but it could be easier to structure and read.

</div>

**Comment by federicotdn** [comment]
More context:
![Screenshot from 2024-10-24 22-07-31](https://github.com/user-attachments/assets/a24718e0-da4a-4345-af2f-b8f3248f90af)

**Comment by agoodno** [comment]
I'm loving this package and it's already changed how I work daily with the APIs I build.

fwiw, I like this style best:

```
:Verb-Prelude+: (verb-set-var "id" "73c02a16-99b9-4ab0-8fd0-fd31a92298f1")
:Verb-Prelude+: (verb-set-var "anotherId" "8491d155-edd8-4831-9e6a-32d939cd35c5")
```

The elisp is identical to what would be in a `.el` file so it can be copied and pasted here easily as an override of variables originally set in the Prelude at the top of the file.

**Comment by federicotdn** [comment]
Implemented here! https://github.com/federicotdn/verb/commit/0e62e4055cfcb5d057987c7d81cba3536d3b0fb7
docs: https://github.com/federicotdn/verb#inline-preludes
