### ISSUE TITLE
How can I make the external prelude .el file marked as safe to load?

### ISSUE THREAD

**Issue by oscarvarto** [federicotdn/verb#80]
Hi!

Whenever I try to execute a request, I get a message like:
```
File prelude.el may contain code that may not be safe
Load it anyways? (y or n)
```

It's very annoying to have to repeatedly do this. How can I mark the prelude.el as safe to load always?

**Comment by oscarvarto** [comment]
I think I found the answer in the source code. I have to customize `verb-suppress-load-unsecure-prelude-warning` variable, and make it non-nil.

I thought it was an Emacs thing, not a particular behavior of the package. Maybe it would be useful to add a brief mention of this variable in the README.

**Comment by federicotdn** [comment]
Thanks for reporting this, I updated the message here: https://github.com/federicotdn/verb/commit/877cda783ab5836e8ce148884f58058f9109d0ee
